= veracode-gradle-plugin
:toc:

Veracode Gradle Plugin that automates Veracode application security scanning activities.

As a set of Gradle tasks, it is meant to be usable either as a command line submission tool or integrated as part of a continuous integration build process.

It helps perform the following tasks:

* Perform Veracode submissions for applications.
* Scan results for flaws.

== Pre-Requisites

* Veracode account & application to perform scanning.
* Veracode Java API JAR file (copy to `lib` directory).
The https://tools.veracode.com/integrations/API-Wrappers/Java/bin/VeracodeJavaAPI.zip[zip file] is found in the https://analysiscenter.veracode.com/auth/helpCenter/api/c_about_wrappers.html[documentation] from Veracode's website.
* JDK 7+ is a requirement for the Veracode Java API.

== Getting Started

=== Compile and publish the project

* Clone the project.

* Copy the `VeracodeJavaAPI.jar` (from Veracode) to a newly created `lib` directory in the root of the project.

* Build and publish to mavenLocal by running:
+
`gradle publish`

=== Apply the plugin into your project

* Create a new Gradle project.

* Copy the `VeracodeJavaAPI.jar` (from Veracode) to a newly created `lib` directory within your project.

* Apply the plugin:
+
[source,groovy]
----
apply plugin: 'groovy'

buildscript {
    apply plugin: 'groovy'
    repositories {
        // For locally published plugin
        mavenLocal()
        // For transitive dependencies
        mavenCentral()
    }
    dependencies {
        classpath files('./lib/VeracodeJavaAPI.jar')
        classpath 'com.calgaryscientific.gradle:veracodePlugin:1.0-SNAPSHOT'
    }
}

apply plugin: 'com.calgaryscientific.gradle.veracode'

veracodeSetup {
    username = "$veracodeUsername" <1>
    password = "$veracodePassword"
    id = "$veracodeID" <1>
    key = "$veracodeKey"
    filesToUpload = fileTree(dir: "upload/", include: "*").getFiles()
    moduleWhitelist = ['class1.jar', 'class2.jar']
}
----
<1> You are only required to use either username and password combination or API id and key.

* Rename the `sample-gradle.properties` file to `gradle.properties` within your project and edit its contents to setup Veracode credentials.
Optionally, the Veracode credentials properties can be placed in the `~/.gradle/gradle.properties` file.

* Execute `gradle tasks` to see available tasks.

== Compatibility

Tested with the Java API version: `VeracodeJavaAPI v17.6.4.4 c201706231537`

Tested with the following XML file versions:

* buildinfo: buildinfo_version="1.4"
* detailedreport: report_format_version="1.5"
* buildlist: buildlist_version="1.3"
* filelist: filelist_version="1.1"

== LICENSE

MIT License

Copyright (c) 2017 Calgary Scientific Incorporated

Copyright (c) 2013-2014 kctang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
